FLASK_APP=main.py

DB_HOST=remotemysql.com
DB_DATABASE=CIvte6ww4R
DB_USERNAME=CIvte6ww4R
DB_PASSWORD=qZLXwzRDvO

TWITTER_CONSUMER_KEY= "tVSOrJIfWcnpRCtZtTWnudwvy"
TWITTER_CONSUMER_SECRET= "dMPSbOt6UWXna7HNwLa4Qy14UaIlojjPzYgHtHo0wJTqXW53NN"
ACCESS_TOKEN_KEY= "2361187837-d02EzmDIeRbMZ7fQ8n5e7Gl0aC7gmygZMNGvTSc"
ACCESS_TOKEN_SECRET= "lMjLxPaq8a6V4oANFOKbWJqqU0TYrzeDRXs1ENnHnxLMW"